Repository KDT3MiniProjectTeam-7/Mini_Project_BE, pull requests merged in 2023-02, with the labels that each got.

#1 feature: 도메인별 entity 생성 및 DB connect 설정
  .gitignore
  build.gradle
  src/main/java/com/example/finance7/MiniProjectBeApplication.java
  src/main/java/com/example/finance7/cart/entity/Cart.java
  src/main/java/com/example/finance7/member/entity/Member.java
  src/main/java/com/example/finance7/member/entity/RecentProduct.java
  src/main/java/com/example/finance7/member/entity/Scession.java
  src/main/java/com/example/finance7/member/entity/SearchHistory.java
  src/main/java/com/example/finance7/product/entity/Card.java
  src/main/java/com/example/finance7/product/entity/Loan.java
  src/main/java/com/example/finance7/product/entity/Product.java
  src/main/java/com/example/finance7/product/entity/Savings.java
  src/main/java/com/example/finance7/product/entity/Subscription.java
  src/main/resources/application.properties
Labels: Priority : High, Status : In Progress, Type : Feature, For : Backend

#2 test: 데이터 입력 관련 테스트 생성
  src/main/java/com/example/finance7/member/entity/RecentProduct.java
  src/main/java/com/example/finance7/member/entity/SearchHistory.java
  src/main/java/com/example/finance7/member/repository/MemberRepository.java
  src/main/java/com/example/finance7/product/entity/Product.java
  src/main/java/com/example/finance7/product/entity/Subscription.java
  src/main/java/com/example/finance7/product/repository/CardRepository.java
  src/main/java/com/example/finance7/product/repository/LoanRepository.java
  src/main/java/com/example/finance7/product/repository/SavingsRepository.java
  src/main/java/com/example/finance7/product/repository/SubscriptionRepository.java
  src/main/resources/application.properties
  src/test/java/com/example/finance7/CreateDataTest.java
  src/test/java/com/example/finance7/MiniProjectBeApplicationTests.java
Labels: Priority : High, Status : In Progress, Type : Feature, For : Backend

#10 fix: Product 도메인 엔티티 수정
  src/main/java/com/example/finance7/product/entity/Card.java
  src/main/java/com/example/finance7/product/entity/Subscription.java
Labels: Priority : Ciritical, Status : Completed, Type : Bug, For : Backend

#11 feature : 장바구니 상품 추가 API 구현
  src/main/java/com/example/finance7/cart/controller/CartController.java
  src/main/java/com/example/finance7/cart/repository/CartRepository.java
  src/main/java/com/example/finance7/cart/service/CartService.java
  src/main/java/com/example/finance7/cart/service/impl/CartServiceImpl.java
  src/main/java/com/example/finance7/cart/vo/SimpleVO.java
  src/test/java/com/example/finance7/cart/service/impl/CartServiceImplTest.java
Labels: Status : Completed, Priority : Medium, For : API, Type : Feature

#12 feature: 상품 상세정보 API 구현
  src/main/java/com/example/finance7/product/controller/ProductController.java
  src/main/java/com/example/finance7/product/dto/CardResponseDTO.java
  src/main/java/com/example/finance7/product/dto/LoanResponseDTO.java
  src/main/java/com/example/finance7/product/dto/ProductResponseDTO.java
  src/main/java/com/example/finance7/product/dto/SavingResponseDTO.java
  src/main/java/com/example/finance7/product/dto/SubscriptionResponseDTO.java
  src/main/java/com/example/finance7/product/repository/ProductRepository.java
  src/main/java/com/example/finance7/product/service/ProductService.java
  src/main/java/com/example/finance7/product/service/impl/ProductServiceImpl.java
  src/main/java/com/example/finance7/product/vo/ProductResponseVO.java
Labels: Status : Completed, Priority : Medium, For : API, Type : Feature, For : Backend

#13 feature: 로그인 API 구현
  build.gradle
  src/main/java/com/example/finance7/member/controller/MemberController.java
  src/main/java/com/example/finance7/member/dto/MemberRequestDTO.java
  src/main/java/com/example/finance7/member/dto/MemberResponseDTO.java
  src/main/java/com/example/finance7/member/entity/Member.java
  src/main/java/com/example/finance7/member/repository/MemberRepository.java
  src/main/java/com/example/finance7/member/service/MemberService.java
  src/main/java/com/example/finance7/member/service/impl/MemberServiceImpl.java
  src/main/java/com/example/finance7/member/vo/MemberVO.java
Labels: Priority : High, Status : In Progress, For : API, Type : Feature

#15 feature: 장바구니 조회 기능 구현
  src/main/java/com/example/finance7/cart/controller/CartController.java
  src/main/java/com/example/finance7/cart/dto/AddCartRequestDTO.java
  src/main/java/com/example/finance7/cart/dto/CardResponseDTO.java
  src/main/java/com/example/finance7/cart/dto/LoanResponseDTO.java
  src/main/java/com/example/finance7/cart/dto/ProductResponseDTO.java
  src/main/java/com/example/finance7/cart/dto/SavingResponseDTO.java
  src/main/java/com/example/finance7/cart/dto/SubscriptionResponseDTO.java
  src/main/java/com/example/finance7/cart/repository/CartRepository.java
  src/main/java/com/example/finance7/cart/service/CartService.java
  src/main/java/com/example/finance7/cart/service/impl/CartServiceImpl.java
  src/main/java/com/example/finance7/cart/vo/CartVO.java
  src/main/java/com/example/finance7/member/service/MemberService.java
  src/main/java/com/example/finance7/member/service/impl/MemberServiceImpl.java
  src/main/java/com/example/finance7/product/repository/ProductRepository.java
  src/main/java/com/example/finance7/product/service/ProductService.java
  src/main/java/com/example/finance7/product/service/impl/ProductServiceImpl.java
  src/test/java/com/example/finance7/cart/service/impl/CartServiceImplTest.java
Labels: Status : Completed, Priority : Medium, For : API, Type : Feature

#16 feature: 추천 상품 조회 기능 구현
  src/main/java/com/example/finance7/product/controller/ProductController.java
  src/main/java/com/example/finance7/product/service/ProductService.java
  src/main/java/com/example/finance7/product/service/impl/ProductServiceImpl.java
Labels: Status : Completed, Priority : High, For : API, Type : Feature, For : Backend

#17 feature: 회원가입 / 로그아웃 기능 구현
  src/main/java/com/example/finance7/member/controller/MemberController.java
  src/main/java/com/example/finance7/member/repository/MemberRepository.java
  src/main/java/com/example/finance7/member/service/MemberService.java
  src/main/java/com/example/finance7/member/service/impl/MemberServiceImpl.java
  src/test/java/com/example/finance7/CreateDataTest.java
Labels: Status : In Progress, Priority : Medium, For : API, Type : Feature, For : Backend

#20 feature : 장바구니 상품 삭제 API 구현
  src/main/java/com/example/finance7/cart/controller/CartController.java
  src/main/java/com/example/finance7/cart/dto/CartRequestDTO.java
  src/main/java/com/example/finance7/cart/repository/CartRepository.java
  src/main/java/com/example/finance7/cart/service/CartService.java
  src/main/java/com/example/finance7/cart/service/impl/CartServiceImpl.java
Labels: Status : Completed, Priority : Medium, For : API, Type : Feature

#18 feature : 회원정보 조회 및 수정 기능 구현
  src/main/java/com/example/finance7/member/controller/MemberInfoController.java
  src/main/java/com/example/finance7/member/dto/SomeMemberInfoResponse.java
  src/main/java/com/example/finance7/member/dto/SomeMemberUpdateInfoDto.java
  src/main/java/com/example/finance7/member/dto/SomeMemberUpdateInfoRequest.java
  src/main/java/com/example/finance7/member/dto/StatusResponse.java
  src/main/java/com/example/finance7/member/entity/Member.java
  src/main/java/com/example/finance7/member/service/MemberInfoService.java
  src/main/java/com/example/finance7/member/service/impl/MemberInfoServiceImpl.java
Labels: Status : Completed, Priority : Medium, For : API, Type : Feature

#23 카테고리별 검색 결과 조회 관련 서비스 구현
  src/main/java/com/example/finance7/product/controller/ProductController.java
  src/main/java/com/example/finance7/product/repository/CardRepository.java
  src/main/java/com/example/finance7/product/repository/LoanRepository.java
  src/main/java/com/example/finance7/product/repository/ProductRepository.java
  src/main/java/com/example/finance7/product/repository/SavingsRepository.java
  src/main/java/com/example/finance7/product/repository/SubscriptionRepository.java
  src/main/java/com/example/finance7/product/service/ProductService.java
  src/main/java/com/example/finance7/product/service/impl/ProductServiceImpl.java
  src/main/java/com/example/finance7/product/vo/ProductResponsePagingVO.java
Labels: Status : Completed, Priority : High, For : API, Type : Feature, For : Backend

#24 feature : 장바구니 전체 삭제 API 구현
  src/main/java/com/example/finance7/cart/controller/CartController.java
  src/main/java/com/example/finance7/cart/dto/DeleteResponseDTO.java
  src/main/java/com/example/finance7/cart/repository/CartRepository.java
  src/main/java/com/example/finance7/cart/service/CartService.java
  src/main/java/com/example/finance7/cart/service/impl/CartServiceImpl.java
  src/main/java/com/example/finance7/member/service/MemberService.java
  src/main/java/com/example/finance7/member/service/impl/MemberServiceImpl.java
  src/test/java/com/example/finance7/cart/service/impl/CartServiceImplTest.java
Labels: Status : Completed, Priority : Medium, For : API, Type : Feature

#26 refactor: 회원가입, 로그인 기능 수정
  src/main/java/com/example/finance7/member/controller/MemberController.java
  src/main/java/com/example/finance7/member/dto/MemberRequestDTO.java
  src/main/java/com/example/finance7/member/dto/MemberResponseDTO.java
  src/main/java/com/example/finance7/member/entity/Member.java
  src/main/java/com/example/finance7/member/service/impl/MemberServiceImpl.java
  src/main/java/com/example/finance7/member/vo/MemberVO.java
Labels: Status : In Progress, Priority : Medium, For : API, Type : Feature, For : Backend

#25 카테고리별 상품 조회 및 최근 검색어 조회 API구현
  src/main/java/com/example/finance7/member/controller/MemberInfoController.java
  src/main/java/com/example/finance7/member/dto/MemberSearchHistoryResponseDTO.java
  src/main/java/com/example/finance7/member/repository/SearchHistoryRepository.java
  src/main/java/com/example/finance7/member/service/MemberInfoService.java
  src/main/java/com/example/finance7/member/service/impl/MemberInfoServiceImpl.java
  src/main/java/com/example/finance7/member/vo/MemberSearchHistoryResponseVO.java
  src/main/java/com/example/finance7/product/controller/ProductController.java
  src/main/java/com/example/finance7/product/dto/ProductResponseDTO.java
  src/main/java/com/example/finance7/product/repository/CardRepository.java
  src/main/java/com/example/finance7/product/repository/LoanRepository.java
  src/main/java/com/example/finance7/product/repository/ProductRepository.java
  src/main/java/com/example/finance7/product/repository/SavingsRepository.java
  src/main/java/com/example/finance7/product/repository/SubscriptionRepository.java
  src/main/java/com/example/finance7/product/service/ProductService.java
  src/main/java/com/example/finance7/product/service/impl/ProductServiceImpl.java
  src/main/java/com/example/finance7/product/vo/ProductResponseRecommendationGroupByCategory.java
  src/test/java/com/example/finance7/member/service/impl/MemberInfoServiceImplTest.java
Labels: Priority : Ciritical, Status : Completed, For : API, Type : Feature, For : Backend

#27 feature : 최근 검색어와 관련된 API들을 구현했습니다.
  src/main/java/com/example/finance7/cart/service/impl/CartServiceImpl.java
  src/main/java/com/example/finance7/member/controller/MemberInfoController.java
  src/main/java/com/example/finance7/member/dto/DeleteAllResponseDTO.java
  src/main/java/com/example/finance7/member/dto/DeleteKeywordRequestDTO.java
  src/main/java/com/example/finance7/member/dto/KeywordRequest.java
  src/main/java/com/example/finance7/member/repository/SearchHistoryRepository.java
  src/main/java/com/example/finance7/member/service/MemberInfoService.java
  src/main/java/com/example/finance7/member/service/impl/MemberInfoServiceImpl.java
Labels: Status : Completed, Priority : Medium, For : API, Type : Feature

#28 feature: 회원 정보 수정 및 최근 본 상품 조회 및 추가 구현
  src/main/java/com/example/finance7/member/controller/MemberInfoController.java
  src/main/java/com/example/finance7/member/controller/RecentProductController.java
  src/main/java/com/example/finance7/member/dto/MemberInfoResponseDTO.java
  src/main/java/com/example/finance7/member/dto/MemberInfoUpdateRequestDTO.java
  src/main/java/com/example/finance7/member/dto/RecentProductRequestDTO.java
  src/main/java/com/example/finance7/member/dto/RecentProductsResponseDTO.java
  src/main/java/com/example/finance7/member/dto/SomeMemberUpdateInfoDto.java
  src/main/java/com/example/finance7/member/dto/SomeMemberUpdateInfoRequest.java
  src/main/java/com/example/finance7/member/dto/StatusResponseDTO.java
  src/main/java/com/example/finance7/member/entity/Member.java
  src/main/java/com/example/finance7/member/repository/RecentProductRepository.java
  src/main/java/com/example/finance7/member/service/MemberInfoService.java
  src/main/java/com/example/finance7/member/service/RecentProductService.java
  src/main/java/com/example/finance7/member/service/impl/MemberInfoServiceImpl.java
  src/main/java/com/example/finance7/member/service/impl/RecentProductServiceImpl.java
  src/main/java/com/example/finance7/member/vo/RecentProductInfoVO.java
Labels: Status : Completed, Priority : Medium, For : API, Type : Feature

#29 fix: conflict문제 해결
  src/main/java/com/example/finance7/member/controller/MemberInfoController.java
  src/main/java/com/example/finance7/member/service/MemberInfoService.java
  src/main/java/com/example/finance7/member/service/impl/MemberInfoServiceImpl.java
Labels: Status : Completed, Priority : High, For : API, Type : Feature

#31 feature : 맞춤 테스트 관련된 API 서비스를 구현했습니다.
  src/main/java/com/example/finance7/member/controller/MemberSurveyController.java
  src/main/java/com/example/finance7/member/entity/Member.java
  src/main/java/com/example/finance7/member/service/MemberSurveyService.java
  src/main/java/com/example/finance7/member/service/impl/MemberInfoServiceImpl.java
  src/main/java/com/example/finance7/member/service/impl/MemberSurveyServiceImpl.java
Labels: Priority : Ciritical, Status : Completed, For : API, Type : Feature, For : Backend

#33 conf : logback 설정을 완료했습니다.
  .gitignore
  src/main/java/com/example/finance7/aop/LogAdvice.java
Labels: Status : Completed, Priority : High, For : Backend, Type : Maintenance, For : CLI

#35 feature: 회원 정보 조회 시 생일 정보 추가
  src/main/java/com/example/finance7/member/controller/MemberInfoController.java
  src/main/java/com/example/finance7/member/dto/MemberInfoResponseDTO.java
  src/main/java/com/example/finance7/member/entity/Member.java
  src/main/java/com/example/finance7/member/service/impl/MemberInfoServiceImpl.java
Labels: Status : Completed, Priority : Medium, For : API, Type : Feature

#36 refactor: tag가 들어오지 않았을때 로직 구현과 dto를 수정했습니다.
  src/main/java/com/example/finance7/member/service/impl/MemberSurveyServiceImpl.java
  src/main/java/com/example/finance7/product/dto/ProductResponseDTO.java
  src/main/java/com/example/finance7/product/service/impl/ProductServiceImpl.java
Labels: Priority : Ciritical, Status : Completed, Type : Bug, For : API, For : Backend

#37 refactor: 오류 수정 및 예외 처리
  src/main/java/com/example/finance7/member/entity/Member.java
  src/main/java/com/example/finance7/member/service/impl/MemberInfoServiceImpl.java
  src/main/java/com/example/finance7/member/service/impl/RecentProductServiceImpl.java
Labels: Status : Completed, Priority : Medium, For : API, Type : Feature

#38 refactor: logout 응답 형식 변경 및 예외처리
  src/main/java/com/example/finance7/member/controller/MemberController.java
  src/main/java/com/example/finance7/member/service/MemberService.java
  src/main/java/com/example/finance7/member/service/impl/MemberServiceImpl.java
Labels: Status : Completed, Priority : Low, For : API, Type : Feature

#39 fix: 중복 검색어 추가 시 제일 위로 오도록 변경
  src/main/java/com/example/finance7/member/repository/SearchHistoryRepository.java
  src/main/java/com/example/finance7/member/service/impl/MemberInfoServiceImpl.java
Labels: Status : Completed, Priority : Medium, For : API, Type : Feature

#40 fix: 회원정보 및 최근 본 상품의 필요없는 어노테이션, 예외 문구 삭제
  src/main/java/com/example/finance7/member/controller/MemberInfoController.java
  src/main/java/com/example/finance7/member/service/impl/MemberInfoServiceImpl.java
  src/main/java/com/example/finance7/member/service/impl/RecentProductServiceImpl.java
Labels: Status : Completed, Priority : Low, For : API, Type : Feature
